# Por convención deben llamarse action.yml o action.yaml

name: Hola Mundo
description: Esta es mi primer action.
author: 'Ice'

# Esta directiva nos permite pasar parámetros como se hace con with:
inputs:
  message:      # Nombre de la variable
    description: Mensaje a imprimir
    required: true
    default: "Hola"

runs:
  using: composite

  steps:
    - name: Hola Mundo
      shell: bash
      # run: echo "Hola Mundo"
      run: echo "Hola ${{ inputs.message }}"
