# En este action podemos ver como usar contenedores de Docker con los actions.
# https://docs.github.com/es/actions/use-cases-and-examples/using-containerized-services/about-service-containers

name: Servicios

on:
  push:
  workflow_dispatch:

jobs:
  # Nombre del job.
  container-job:   
    runs-on: ubuntu-latest

    # Contenedores de servicio.
    services:
      # Etiqueta para el contenedor.
      hello-world:
        image: hello-world

      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: example
        ports:
          - 3306:3306
      
      # redis:
      #   image: redis
      #   ports:
      #     - 6379:6379

    steps:
      - name: Test
        run: ls
