name: Test

on: [push, workflow_dispatch]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ls
        run: |
          # Dar permisos de ejecución al script
          chmod +x script.sh

          # Ejecutar el script
          ./script.sh

