name: Test

on: [push, workflow_dispatch]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ls
        run: |
          chmod +x script.sh
          ./script.sh
